export const GPS_ERROR_CODES = {
    UNSUPPORTED: 'GPS_UNSUPPORTED',
    PERMISSION_DENIED: 'GPS_PERMISSION_DENIED',
    POSITION_UNAVAILABLE: 'GPS_POSITION_UNAVAILABLE',
    TIMEOUT: 'GPS_TIMEOUT',
    UNKNOWN: 'GPS_UNKNOWN'
} as const;
